"""users_auth_guest_store_campaign

Revision ID: 871a50acc488
Revises: 202608130001
Create Date: 2026-08-14 01:16:38.518660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871a50acc488'
down_revision: Union[str, None] = '202608130001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('startsAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endsAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign'))
    )
    op.create_table('store',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store'))
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('authProvider', sa.Enum('local', 'google', 'kakao', name='authProvider'), nullable=False),
    sa.Column('providerUserId', sa.String(length=255), nullable=True),
    sa.Column('passwordHash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('loginFailCount', sa.Integer(), nullable=False),
    sa.Column('lockedUntil', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('authProvider', 'providerUserId', name='uq_user_provider_identity')
    )
    # LOCAL accounts: email unique among active (non-deleted) accounts only.
    # Social accounts may share the same email as a LOCAL one (separate accounts).
    op.create_index(
        'uq_user_local_email_active',
        'user',
        ['email'],
        unique=True,
        postgresql_where=sa.text('"authProvider" = \'local\' AND "deletedAt" IS NULL'),
    )
    op.create_table('qrCodeMapping',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('storeId', sa.Uuid(), nullable=True),
    sa.Column('campaignId', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaignId'], ['campaign.id'], name=op.f('fk_qrCodeMapping_campaignId_campaign')),
    sa.ForeignKeyConstraint(['storeId'], ['store.id'], name=op.f('fk_qrCodeMapping_storeId_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qrCodeMapping')),
    sa.UniqueConstraint('code', name=op.f('uq_qrCodeMapping_code'))
    )
    op.create_table('refreshToken',
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('tokenHash', sa.String(length=255), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revokedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_refreshToken_userId_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refreshToken')),
    sa.UniqueConstraint('tokenHash', name=op.f('uq_refreshToken_tokenHash'))
    )
    op.create_index(op.f('ix_refreshToken_userId'), 'refreshToken', ['userId'], unique=False)
    op.create_table('guestSession',
    sa.Column('qrCodeId', sa.Uuid(), nullable=True),
    sa.Column('heightCm', sa.Numeric(), nullable=True),
    sa.Column('weightKg', sa.Numeric(), nullable=True),
    sa.Column('gender', sa.Enum('female', 'male', 'neutral', name='gender'), nullable=True),
    sa.Column('photoTryOnCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['qrCodeId'], ['qrCodeMapping.id'], name=op.f('fk_guestSession_qrCodeId_qrCodeMapping')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guestSession'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guestSession')
    op.drop_index(op.f('ix_refreshToken_userId'), table_name='refreshToken')
    op.drop_table('refreshToken')
    op.drop_table('qrCodeMapping')
    op.drop_index('uq_user_local_email_active', table_name='user')
    op.drop_table('user')
    op.drop_table('store')
    op.drop_table('campaign')
    # ### end Alembic commands ###
