"""products_variants_tags_images

Revision ID: 0a47cf24eddf
Revises: 871a50acc488
Create Date: 2026-08-14 01:40:31.228591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a47cf24eddf'
down_revision: Union[str, None] = '871a50acc488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('productCode', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('basePrice', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('productCode', name=op.f('uq_product_productCode'))
    )
    op.create_table('productImage',
    sa.Column('productId', sa.Uuid(), nullable=False),
    sa.Column('fileId', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name=op.f('fk_productImage_productId_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productImage'))
    )
    op.create_index(op.f('ix_productImage_productId'), 'productImage', ['productId'], unique=False)
    op.create_table('productTag',
    sa.Column('productId', sa.Uuid(), nullable=False),
    sa.Column('tagType', sa.String(length=40), nullable=False),
    sa.Column('tagValue', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name=op.f('fk_productTag_productId_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productTag'))
    )
    op.create_index('ix_productTag_productId', 'productTag', ['productId'], unique=False)
    op.create_table('productVariant',
    sa.Column('productId', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('size', sa.String(length=80), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name=op.f('fk_productVariant_productId_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productVariant')),
    sa.UniqueConstraint('sku', name=op.f('uq_productVariant_sku'))
    )
    op.create_index('ix_productVariant_productId_active', 'productVariant', ['productId', 'active'], unique=False)
    op.create_index('ix_productVariant_productId_color_size', 'productVariant', ['productId', 'color', 'size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productVariant_productId_color_size', table_name='productVariant')
    op.drop_index('ix_productVariant_productId_active', table_name='productVariant')
    op.drop_table('productVariant')
    op.drop_index('ix_productTag_productId', table_name='productTag')
    op.drop_table('productTag')
    op.drop_index(op.f('ix_productImage_productId'), table_name='productImage')
    op.drop_table('productImage')
    op.drop_table('product')
    # ### end Alembic commands ###
