"""recent_products

Revision ID: 0e50adfd7c72
Revises: 0a47cf24eddf
Create Date: 2026-08-14 02:10:23.717503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e50adfd7c72'
down_revision: Union[str, None] = '0a47cf24eddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recentProduct',
    sa.Column('userId', sa.Uuid(), nullable=True),
    sa.Column('guestSessionId', sa.Uuid(), nullable=True),
    sa.Column('productId', sa.Uuid(), nullable=False),
    sa.Column('viewedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('("userId" IS NOT NULL) <> ("guestSessionId" IS NOT NULL)', name=op.f('ck_recentProduct_ck_recentProduct_one_owner')),
    sa.ForeignKeyConstraint(['guestSessionId'], ['guestSession.id'], name=op.f('fk_recentProduct_guestSessionId_guestSession'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name=op.f('fk_recentProduct_productId_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_recentProduct_userId_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recentProduct'))
    )
    op.create_index('ix_recentProduct_guestSessionId_viewedAt', 'recentProduct', ['guestSessionId', 'viewedAt'], unique=False)
    op.create_index('ix_recentProduct_userId_viewedAt', 'recentProduct', ['userId', 'viewedAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recentProduct_userId_viewedAt', table_name='recentProduct')
    op.drop_index('ix_recentProduct_guestSessionId_viewedAt', table_name='recentProduct')
    op.drop_table('recentProduct')
    # ### end Alembic commands ###
