"""cart

Revision ID: 58772b2f23fc
Revises: 0e50adfd7c72
Create Date: 2026-08-14 02:16:37.233443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58772b2f23fc'
down_revision: Union[str, None] = '0e50adfd7c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_cart_userId_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart')),
    sa.UniqueConstraint('userId', name=op.f('uq_cart_userId'))
    )
    op.create_table('cartItem',
    sa.Column('cartId', sa.Uuid(), nullable=False),
    sa.Column('variantId', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cartId'], ['cart.id'], name=op.f('fk_cartItem_cartId_cart'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variantId'], ['productVariant.id'], name=op.f('fk_cartItem_variantId_productVariant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cartItem')),
    sa.UniqueConstraint('cartId', 'variantId', name='uq_cartItem_cartId_variantId')
    )
    op.create_index(op.f('ix_cartItem_cartId'), 'cartItem', ['cartId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartItem_cartId'), table_name='cartItem')
    op.drop_table('cartItem')
    op.drop_table('cart')
    # ### end Alembic commands ###
