"""orders_payments_registered

Revision ID: dc6572a22ce7
Revises: 58772b2f23fc
Create Date: 2026-08-14 02:22:34.601673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc6572a22ce7'
down_revision: Union[str, None] = '58772b2f23fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'cancelled', name='orderStatus'), nullable=False),
    sa.Column('totalAmount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paidAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_order_userId_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    op.create_index(op.f('ix_order_userId'), 'order', ['userId'], unique=False)
    op.create_table('orderItem',
    sa.Column('orderId', sa.Uuid(), nullable=False),
    sa.Column('productId', sa.Uuid(), nullable=False),
    sa.Column('variantId', sa.Uuid(), nullable=False),
    sa.Column('productNameSnapshot', sa.String(length=255), nullable=False),
    sa.Column('variantSnapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unitPrice', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lineAmount', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], name=op.f('fk_orderItem_orderId_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name=op.f('fk_orderItem_productId_product')),
    sa.ForeignKeyConstraint(['variantId'], ['productVariant.id'], name=op.f('fk_orderItem_variantId_productVariant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderItem'))
    )
    op.create_index(op.f('ix_orderItem_orderId'), 'orderItem', ['orderId'], unique=False)
    op.create_table('payment',
    sa.Column('orderId', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('providerPaymentId', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ready', 'success', 'failed', 'cancelled', 'refunded', name='paymentStatus'), nullable=False),
    sa.Column('failureCode', sa.String(length=60), nullable=True),
    sa.Column('failureMessage', sa.String(length=255), nullable=True),
    sa.Column('approvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], name=op.f('fk_payment_orderId_order'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index(op.f('ix_payment_orderId'), 'payment', ['orderId'], unique=False)
    op.create_table('registeredProduct',
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('productId', sa.Uuid(), nullable=False),
    sa.Column('orderItemId', sa.Uuid(), nullable=True),
    sa.Column('serialNumber', sa.String(length=150), nullable=True),
    sa.Column('source', sa.Enum('purchase', 'manual', name='registeredProductSource'), nullable=False),
    sa.Column('purchaseDate', sa.Date(), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['orderItemId'], ['orderItem.id'], name=op.f('fk_registeredProduct_orderItemId_orderItem')),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name=op.f('fk_registeredProduct_productId_product')),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_registeredProduct_userId_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registeredProduct'))
    )
    op.create_index('ix_registeredProduct_serialNumber', 'registeredProduct', ['serialNumber'], unique=False)
    op.create_index('ix_registeredProduct_userId_createdAt', 'registeredProduct', ['userId', 'createdAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registeredProduct_userId_createdAt', table_name='registeredProduct')
    op.drop_index('ix_registeredProduct_serialNumber', table_name='registeredProduct')
    op.drop_table('registeredProduct')
    op.drop_index(op.f('ix_payment_orderId'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_orderItem_orderId'), table_name='orderItem')
    op.drop_table('orderItem')
    op.drop_index(op.f('ix_order_userId'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
