"""product_care_guide

Revision ID: 1938b1e76060
Revises: dc6572a22ce7
Create Date: 2026-08-14 02:35:11.794138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1938b1e76060'
down_revision: Union[str, None] = 'dc6572a22ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productCareGuide',
    sa.Column('productId', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('guideJson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asInfoJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], name=op.f('fk_productCareGuide_productId_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productCareGuide'))
    )
    op.create_index('ix_productCareGuide_productId', 'productCareGuide', ['productId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productCareGuide_productId', table_name='productCareGuide')
    op.drop_table('productCareGuide')
    # ### end Alembic commands ###
